version: '3.8'

services:
  carbon-explorer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=${NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN}
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PORT=8000
    restart: always
